#############################################################################
# Makefile for building: SparkZNC
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Tue Jun 24 09:20:35 2014
# Project:  SparkZNC.pro
# Template: app
# Command: $(QMAKE) -o Makefile SparkZNC.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
CXXFLAGS = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -I/usr/include/qt3
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = en_keymap.h \
		fm25v02.h \
		fpga.h \
		qcheck.h \
		qcombox.h \
		qcomboxtime.h \
		qcommand.h \
		qindicate.h \
		qparameter.h \
		scanthread.h \
		setting.h \
		sparkinfo.h \
		sparkthread.h
SOURCES = fm25v02.c \
		fpga.c \
		main.cpp \
		qcheck.cpp \
		qcombox.cpp \
		qcomboxtime.cpp \
		qcommand.cpp \
		qindicate.cpp \
		qparameter.cpp \
		scanthread.cpp \
		sparkinfo.cpp \
		sparkthread.cpp
OBJECTS = fm25v02.o \
		fpga.o \
		main.o \
		qcheck.o \
		qcombox.o \
		qcomboxtime.o \
		qcommand.o \
		qindicate.o \
		qparameter.o \
		scanthread.o \
		sparkinfo.o \
		sparkthread.o \
		autodialog.o \
		coordialog.o \
		groupdialog.o \
		jumpdialog.o \
		keyboard.o \
		maininterface.o \
		mesgbox.o \
		seconlevel_f3.o \
		seconlevel_f4.o \
		seconlevel_f5.o \
		seconlevel_f6.o \
		toplevel.o
FORMS = autodialog.ui \
		coordialog.ui \
		groupdialog.ui \
		jumpdialog.ui \
		keyboard.ui \
		maininterface.ui \
		mesgbox.ui \
		seconlevel_f3.ui \
		seconlevel_f4.ui \
		seconlevel_f5.ui \
		seconlevel_f6.ui \
		toplevel.ui
UICDECLS = autodialog.h \
		coordialog.h \
		groupdialog.h \
		jumpdialog.h \
		keyboard.h \
		maininterface.h \
		mesgbox.h \
		seconlevel_f3.h \
		seconlevel_f4.h \
		seconlevel_f5.h \
		seconlevel_f6.h \
		toplevel.h
UICIMPLS = autodialog.cpp \
		coordialog.cpp \
		groupdialog.cpp \
		jumpdialog.cpp \
		keyboard.cpp \
		maininterface.cpp \
		mesgbox.cpp \
		seconlevel_f3.cpp \
		seconlevel_f4.cpp \
		seconlevel_f5.cpp \
		seconlevel_f6.cpp \
		toplevel.cpp
SRCMOC   = moc_qcheck.cpp \
		moc_qcombox.cpp \
		moc_qcomboxtime.cpp \
		moc_qcommand.cpp \
		moc_qindicate.cpp \
		moc_qparameter.cpp \
		moc_scanthread.cpp \
		moc_sparkinfo.cpp \
		moc_sparkthread.cpp \
		moc_autodialog.cpp \
		moc_coordialog.cpp \
		moc_groupdialog.cpp \
		moc_jumpdialog.cpp \
		moc_keyboard.cpp \
		moc_maininterface.cpp \
		moc_mesgbox.cpp \
		moc_seconlevel_f3.cpp \
		moc_seconlevel_f4.cpp \
		moc_seconlevel_f5.cpp \
		moc_seconlevel_f6.cpp \
		moc_toplevel.cpp
OBJMOC = moc_qcheck.o \
		moc_qcombox.o \
		moc_qcomboxtime.o \
		moc_qcommand.o \
		moc_qindicate.o \
		moc_qparameter.o \
		moc_scanthread.o \
		moc_sparkinfo.o \
		moc_sparkthread.o \
		moc_autodialog.o \
		moc_coordialog.o \
		moc_groupdialog.o \
		moc_jumpdialog.o \
		moc_keyboard.o \
		moc_maininterface.o \
		moc_mesgbox.o \
		moc_seconlevel_f3.o \
		moc_seconlevel_f4.o \
		moc_seconlevel_f5.o \
		moc_seconlevel_f6.o \
		moc_toplevel.o
DIST	   = SparkZNC.pro
QMAKE_TARGET = SparkZNC
DESTDIR  = 
TARGET   = SparkZNC

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: SparkZNC.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile SparkZNC.pro
qmake: 
	@$(QMAKE) -o Makefile SparkZNC.pro

dist: 
	@mkdir -p .tmp/SparkZNC && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/SparkZNC/ && ( cd `dirname .tmp/SparkZNC` && $(TAR) SparkZNC.tar SparkZNC && $(GZIP) SparkZNC.tar ) && $(MOVE) `dirname .tmp/SparkZNC`/SparkZNC.tar.gz . && $(DEL_FILE) -r .tmp/SparkZNC

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:
	-$(DEL_FILE) $(UICIMPLS) $(UICDECLS)

yaccclean:
lexclean:
clean: mocclean uiclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

fm25v02.o: fm25v02.c fm25v02.h \
		setting.h

fpga.o: fpga.c fpga.h \
		setting.h

main.o: main.cpp maininterface.h \
		sparkinfo.h \
		setting.h \
		mesgbox.h \
		toplevel.h \
		seconlevel_f3.h \
		seconlevel_f4.h \
		seconlevel_f5.h \
		seconlevel_f6.h \
		keyboard.h \
		qcommand.h \
		sparkthread.h \
		scanthread.h \
		fm25v02.h \
		fpga.h \
		qcheck.h \
		qcombox.h \
		qcomboxtime.h \
		qindicate.h \
		qparameter.h \
		coordialog.h \
		groupdialog.h \
		autodialog.h \
		jumpdialog.h

qcheck.o: qcheck.cpp qcheck.h \
		sparkinfo.h

qcombox.o: qcombox.cpp qcombox.h \
		sparkinfo.h

qcomboxtime.o: qcomboxtime.cpp qcomboxtime.h \
		setting.h \
		qcombox.h \
		sparkinfo.h \
		fm25v02.h

qcommand.o: qcommand.cpp qcommand.h \
		sparkinfo.h

qindicate.o: qindicate.cpp qindicate.h \
		sparkinfo.h

qparameter.o: qparameter.cpp qparameter.h \
		sparkinfo.h

scanthread.o: scanthread.cpp scanthread.h \
		sparkinfo.h \
		fpga.h

sparkinfo.o: sparkinfo.cpp sparkinfo.h

sparkthread.o: sparkthread.cpp sparkthread.h \
		sparkinfo.h

autodialog.h: autodialog.ui 
	$(UIC) autodialog.ui -o autodialog.h

autodialog.cpp: autodialog.h autodialog.ui 
	$(UIC) autodialog.ui -i autodialog.h -o autodialog.cpp

coordialog.h: coordialog.ui 
	$(UIC) coordialog.ui -o coordialog.h

coordialog.cpp: coordialog.h coordialog.ui 
	$(UIC) coordialog.ui -i coordialog.h -o coordialog.cpp

groupdialog.h: groupdialog.ui 
	$(UIC) groupdialog.ui -o groupdialog.h

groupdialog.cpp: groupdialog.h groupdialog.ui 
	$(UIC) groupdialog.ui -i groupdialog.h -o groupdialog.cpp

jumpdialog.h: jumpdialog.ui 
	$(UIC) jumpdialog.ui -o jumpdialog.h

jumpdialog.cpp: jumpdialog.h jumpdialog.ui 
	$(UIC) jumpdialog.ui -i jumpdialog.h -o jumpdialog.cpp

keyboard.h: keyboard.ui 
	$(UIC) keyboard.ui -o keyboard.h

keyboard.cpp: keyboard.h keyboard.ui 
	$(UIC) keyboard.ui -i keyboard.h -o keyboard.cpp

maininterface.h: maininterface.ui 
	$(UIC) maininterface.ui -o maininterface.h

maininterface.cpp: maininterface.h maininterface.ui 
	$(UIC) maininterface.ui -i maininterface.h -o maininterface.cpp

mesgbox.h: mesgbox.ui 
	$(UIC) mesgbox.ui -o mesgbox.h

mesgbox.cpp: mesgbox.h mesgbox.ui 
	$(UIC) mesgbox.ui -i mesgbox.h -o mesgbox.cpp

seconlevel_f3.h: seconlevel_f3.ui 
	$(UIC) seconlevel_f3.ui -o seconlevel_f3.h

seconlevel_f3.cpp: seconlevel_f3.h seconlevel_f3.ui 
	$(UIC) seconlevel_f3.ui -i seconlevel_f3.h -o seconlevel_f3.cpp

seconlevel_f4.h: seconlevel_f4.ui 
	$(UIC) seconlevel_f4.ui -o seconlevel_f4.h

seconlevel_f4.cpp: seconlevel_f4.h seconlevel_f4.ui 
	$(UIC) seconlevel_f4.ui -i seconlevel_f4.h -o seconlevel_f4.cpp

seconlevel_f5.h: seconlevel_f5.ui 
	$(UIC) seconlevel_f5.ui -o seconlevel_f5.h

seconlevel_f5.cpp: seconlevel_f5.h seconlevel_f5.ui 
	$(UIC) seconlevel_f5.ui -i seconlevel_f5.h -o seconlevel_f5.cpp

seconlevel_f6.h: seconlevel_f6.ui 
	$(UIC) seconlevel_f6.ui -o seconlevel_f6.h

seconlevel_f6.cpp: seconlevel_f6.h seconlevel_f6.ui 
	$(UIC) seconlevel_f6.ui -i seconlevel_f6.h -o seconlevel_f6.cpp

toplevel.h: toplevel.ui 
	$(UIC) toplevel.ui -o toplevel.h

toplevel.cpp: toplevel.h toplevel.ui 
	$(UIC) toplevel.ui -i toplevel.h -o toplevel.cpp

autodialog.o: autodialog.cpp autodialog.h

coordialog.o: coordialog.cpp coordialog.h

groupdialog.o: groupdialog.cpp groupdialog.h

jumpdialog.o: jumpdialog.cpp jumpdialog.h

keyboard.o: keyboard.cpp keyboard.h

maininterface.o: maininterface.cpp maininterface.h

mesgbox.o: mesgbox.cpp mesgbox.h

seconlevel_f3.o: seconlevel_f3.cpp seconlevel_f3.h

seconlevel_f4.o: seconlevel_f4.cpp seconlevel_f4.h

seconlevel_f5.o: seconlevel_f5.cpp seconlevel_f5.h

seconlevel_f6.o: seconlevel_f6.cpp seconlevel_f6.h

toplevel.o: toplevel.cpp toplevel.h

moc_qcheck.o: moc_qcheck.cpp  qcheck.h 

moc_qcombox.o: moc_qcombox.cpp  qcombox.h 

moc_qcomboxtime.o: moc_qcomboxtime.cpp  qcomboxtime.h qcombox.h \
		sparkinfo.h \
		fm25v02.h \
		setting.h

moc_qcommand.o: moc_qcommand.cpp  qcommand.h 

moc_qindicate.o: moc_qindicate.cpp  qindicate.h 

moc_qparameter.o: moc_qparameter.cpp  qparameter.h 

moc_scanthread.o: moc_scanthread.cpp  scanthread.h 

moc_sparkinfo.o: moc_sparkinfo.cpp  sparkinfo.h 

moc_sparkthread.o: moc_sparkthread.cpp  sparkthread.h 

moc_autodialog.o: moc_autodialog.cpp  autodialog.h 

moc_coordialog.o: moc_coordialog.cpp  coordialog.h 

moc_groupdialog.o: moc_groupdialog.cpp  groupdialog.h 

moc_jumpdialog.o: moc_jumpdialog.cpp  jumpdialog.h 

moc_keyboard.o: moc_keyboard.cpp  keyboard.h 

moc_maininterface.o: moc_maininterface.cpp  maininterface.h mesgbox.h \
		toplevel.h \
		seconlevel_f3.h \
		seconlevel_f4.h \
		seconlevel_f5.h \
		seconlevel_f6.h \
		keyboard.h \
		qcommand.h \
		sparkthread.h \
		scanthread.h \
		fm25v02.h \
		fpga.h \
		setting.h \
		qcheck.h \
		qcombox.h \
		qcomboxtime.h \
		qindicate.h \
		qparameter.h \
		sparkinfo.h \
		coordialog.h \
		groupdialog.h \
		autodialog.h \
		jumpdialog.h

moc_mesgbox.o: moc_mesgbox.cpp  mesgbox.h qcheck.h \
		qcombox.h \
		qcomboxtime.h \
		qindicate.h \
		qparameter.h \
		sparkinfo.h \
		fm25v02.h \
		setting.h

moc_seconlevel_f3.o: moc_seconlevel_f3.cpp  seconlevel_f3.h coordialog.h

moc_seconlevel_f4.o: moc_seconlevel_f4.cpp  seconlevel_f4.h groupdialog.h \
		autodialog.h \
		jumpdialog.h

moc_seconlevel_f5.o: moc_seconlevel_f5.cpp  seconlevel_f5.h 

moc_seconlevel_f6.o: moc_seconlevel_f6.cpp  seconlevel_f6.h 

moc_toplevel.o: moc_toplevel.cpp  toplevel.h 

moc_qcheck.cpp: $(MOC) qcheck.h
	$(MOC) qcheck.h -o moc_qcheck.cpp

moc_qcombox.cpp: $(MOC) qcombox.h
	$(MOC) qcombox.h -o moc_qcombox.cpp

moc_qcomboxtime.cpp: $(MOC) qcomboxtime.h
	$(MOC) qcomboxtime.h -o moc_qcomboxtime.cpp

moc_qcommand.cpp: $(MOC) qcommand.h
	$(MOC) qcommand.h -o moc_qcommand.cpp

moc_qindicate.cpp: $(MOC) qindicate.h
	$(MOC) qindicate.h -o moc_qindicate.cpp

moc_qparameter.cpp: $(MOC) qparameter.h
	$(MOC) qparameter.h -o moc_qparameter.cpp

moc_scanthread.cpp: $(MOC) scanthread.h
	$(MOC) scanthread.h -o moc_scanthread.cpp

moc_sparkinfo.cpp: $(MOC) sparkinfo.h
	$(MOC) sparkinfo.h -o moc_sparkinfo.cpp

moc_sparkthread.cpp: $(MOC) sparkthread.h
	$(MOC) sparkthread.h -o moc_sparkthread.cpp

moc_autodialog.cpp: $(MOC) autodialog.h
	$(MOC) autodialog.h -o moc_autodialog.cpp

moc_coordialog.cpp: $(MOC) coordialog.h
	$(MOC) coordialog.h -o moc_coordialog.cpp

moc_groupdialog.cpp: $(MOC) groupdialog.h
	$(MOC) groupdialog.h -o moc_groupdialog.cpp

moc_jumpdialog.cpp: $(MOC) jumpdialog.h
	$(MOC) jumpdialog.h -o moc_jumpdialog.cpp

moc_keyboard.cpp: $(MOC) keyboard.h
	$(MOC) keyboard.h -o moc_keyboard.cpp

moc_maininterface.cpp: $(MOC) maininterface.h
	$(MOC) maininterface.h -o moc_maininterface.cpp

moc_mesgbox.cpp: $(MOC) mesgbox.h
	$(MOC) mesgbox.h -o moc_mesgbox.cpp

moc_seconlevel_f3.cpp: $(MOC) seconlevel_f3.h
	$(MOC) seconlevel_f3.h -o moc_seconlevel_f3.cpp

moc_seconlevel_f4.cpp: $(MOC) seconlevel_f4.h
	$(MOC) seconlevel_f4.h -o moc_seconlevel_f4.cpp

moc_seconlevel_f5.cpp: $(MOC) seconlevel_f5.h
	$(MOC) seconlevel_f5.h -o moc_seconlevel_f5.cpp

moc_seconlevel_f6.cpp: $(MOC) seconlevel_f6.h
	$(MOC) seconlevel_f6.h -o moc_seconlevel_f6.cpp

moc_toplevel.cpp: $(MOC) toplevel.h
	$(MOC) toplevel.h -o moc_toplevel.cpp

####### Install

install:  

uninstall:  

