#############################################################################
# Makefile for building: SparkZNC
# Generated by qmake (2.01a) (Qt 4.8.1) on: Thu Dec 4 15:49:35 2014
# Project:  SparkZNC.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile SparkZNC.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = autodialog.cpp \
		cleardialog.cpp \
		coordialog.cpp \
		fm25v02.c \
		fpga.c \
		groupdialog.cpp \
		jumpdialog.cpp \
		keyboard.cpp \
		keydialog.cpp \
		main.cpp \
		maininterface.cpp \
		mesgbox.cpp \
		myinputpanelcontext.cpp \
		qcheck.cpp \
		qcombox.cpp \
		qcomboxtime.cpp \
		qcommand.cpp \
		qindicate.cpp \
		qparameter.cpp \
		scanthread.cpp \
		seconlevel_f3.cpp \
		seconlevel_f4.cpp \
		seconlevel_f5.cpp \
		seconlevel_f6.cpp \
		settingdialog.cpp \
		sparkinfo.cpp \
		sparkthread.cpp \
		startmenu.cpp \
		toplevel.cpp \
		qalerts.cpp \
		calibration.cpp moc_autodialog.cpp \
		moc_cleardialog.cpp \
		moc_coordialog.cpp \
		moc_groupdialog.cpp \
		moc_jumpdialog.cpp \
		moc_keyboard.cpp \
		moc_keydialog.cpp \
		moc_maininterface.cpp \
		moc_mesgbox.cpp \
		moc_myinputpanelcontext.cpp \
		moc_qcheck.cpp \
		moc_qcombox.cpp \
		moc_qcomboxtime.cpp \
		moc_qcommand.cpp \
		moc_qindicate.cpp \
		moc_qparameter.cpp \
		moc_scanthread.cpp \
		moc_seconlevel_f3.cpp \
		moc_seconlevel_f4.cpp \
		moc_seconlevel_f5.cpp \
		moc_seconlevel_f6.cpp \
		moc_settingdialog.cpp \
		moc_sparkinfo.cpp \
		moc_sparkthread.cpp \
		moc_startmenu.cpp \
		moc_toplevel.cpp \
		moc_qalerts.cpp \
		qrc_resource.cpp
OBJECTS       = autodialog.o \
		cleardialog.o \
		coordialog.o \
		fm25v02.o \
		fpga.o \
		groupdialog.o \
		jumpdialog.o \
		keyboard.o \
		keydialog.o \
		main.o \
		maininterface.o \
		mesgbox.o \
		myinputpanelcontext.o \
		qcheck.o \
		qcombox.o \
		qcomboxtime.o \
		qcommand.o \
		qindicate.o \
		qparameter.o \
		scanthread.o \
		seconlevel_f3.o \
		seconlevel_f4.o \
		seconlevel_f5.o \
		seconlevel_f6.o \
		settingdialog.o \
		sparkinfo.o \
		sparkthread.o \
		startmenu.o \
		toplevel.o \
		qalerts.o \
		calibration.o \
		moc_autodialog.o \
		moc_cleardialog.o \
		moc_coordialog.o \
		moc_groupdialog.o \
		moc_jumpdialog.o \
		moc_keyboard.o \
		moc_keydialog.o \
		moc_maininterface.o \
		moc_mesgbox.o \
		moc_myinputpanelcontext.o \
		moc_qcheck.o \
		moc_qcombox.o \
		moc_qcomboxtime.o \
		moc_qcommand.o \
		moc_qindicate.o \
		moc_qparameter.o \
		moc_scanthread.o \
		moc_seconlevel_f3.o \
		moc_seconlevel_f4.o \
		moc_seconlevel_f5.o \
		moc_seconlevel_f6.o \
		moc_settingdialog.o \
		moc_sparkinfo.o \
		moc_sparkthread.o \
		moc_startmenu.o \
		moc_toplevel.o \
		moc_qalerts.o \
		qrc_resource.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		SparkZNC.pro
QMAKE_TARGET  = SparkZNC
DESTDIR       = 
TARGET        = SparkZNC

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_autodialog.h ui_cleardialog.h ui_coordialog.h ui_groupdialog.h ui_jumpdialog.h ui_keyboard.h ui_keydialog.h ui_maininterface.h ui_mesgbox.h ui_seconlevel_f3.h ui_seconlevel_f4.h ui_seconlevel_f5.h ui_seconlevel_f6.h ui_settingdialog.h ui_startmenu.h ui_toplevel.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: SparkZNC.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile SparkZNC.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile SparkZNC.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SparkZNC1.0.0 || $(MKDIR) .tmp/SparkZNC1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SparkZNC1.0.0/ && $(COPY_FILE) --parents autodialog.h cleardialog.h coordialog.h en_keymap.h fm25v02.h fpga.h groupdialog.h jumpdialog.h keyboard.h keydialog.h maininterface.h mesgbox.h myinputpanelcontext.h qcheck.h qcombox.h qcomboxtime.h qcommand.h qindicate.h qparameter.h scanthread.h seconlevel_f3.h seconlevel_f4.h seconlevel_f5.h seconlevel_f6.h setting.h settingdialog.h sparkinfo.h sparkthread.h startmenu.h toplevel.h qalerts.h calibration.h .tmp/SparkZNC1.0.0/ && $(COPY_FILE) --parents resource.qrc .tmp/SparkZNC1.0.0/ && $(COPY_FILE) --parents autodialog.cpp cleardialog.cpp coordialog.cpp fm25v02.c fpga.c groupdialog.cpp jumpdialog.cpp keyboard.cpp keydialog.cpp main.cpp maininterface.cpp mesgbox.cpp myinputpanelcontext.cpp qcheck.cpp qcombox.cpp qcomboxtime.cpp qcommand.cpp qindicate.cpp qparameter.cpp scanthread.cpp seconlevel_f3.cpp seconlevel_f4.cpp seconlevel_f5.cpp seconlevel_f6.cpp settingdialog.cpp sparkinfo.cpp sparkthread.cpp startmenu.cpp toplevel.cpp qalerts.cpp calibration.cpp .tmp/SparkZNC1.0.0/ && $(COPY_FILE) --parents autodialog.ui cleardialog.ui coordialog.ui groupdialog.ui jumpdialog.ui keyboard.ui keydialog.ui maininterface.ui mesgbox.ui seconlevel_f3.ui seconlevel_f4.ui seconlevel_f5.ui seconlevel_f6.ui settingdialog.ui startmenu.ui toplevel.ui .tmp/SparkZNC1.0.0/ && $(COPY_FILE) --parents en.ts .tmp/SparkZNC1.0.0/ && (cd `dirname .tmp/SparkZNC1.0.0` && $(TAR) SparkZNC1.0.0.tar SparkZNC1.0.0 && $(COMPRESS) SparkZNC1.0.0.tar) && $(MOVE) `dirname .tmp/SparkZNC1.0.0`/SparkZNC1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SparkZNC1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_autodialog.cpp moc_cleardialog.cpp moc_coordialog.cpp moc_groupdialog.cpp moc_jumpdialog.cpp moc_keyboard.cpp moc_keydialog.cpp moc_maininterface.cpp moc_mesgbox.cpp moc_myinputpanelcontext.cpp moc_qcheck.cpp moc_qcombox.cpp moc_qcomboxtime.cpp moc_qcommand.cpp moc_qindicate.cpp moc_qparameter.cpp moc_scanthread.cpp moc_seconlevel_f3.cpp moc_seconlevel_f4.cpp moc_seconlevel_f5.cpp moc_seconlevel_f6.cpp moc_settingdialog.cpp moc_sparkinfo.cpp moc_sparkthread.cpp moc_startmenu.cpp moc_toplevel.cpp moc_qalerts.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_autodialog.cpp moc_cleardialog.cpp moc_coordialog.cpp moc_groupdialog.cpp moc_jumpdialog.cpp moc_keyboard.cpp moc_keydialog.cpp moc_maininterface.cpp moc_mesgbox.cpp moc_myinputpanelcontext.cpp moc_qcheck.cpp moc_qcombox.cpp moc_qcomboxtime.cpp moc_qcommand.cpp moc_qindicate.cpp moc_qparameter.cpp moc_scanthread.cpp moc_seconlevel_f3.cpp moc_seconlevel_f4.cpp moc_seconlevel_f5.cpp moc_seconlevel_f6.cpp moc_settingdialog.cpp moc_sparkinfo.cpp moc_sparkthread.cpp moc_startmenu.cpp moc_toplevel.cpp moc_qalerts.cpp
moc_autodialog.cpp: autodialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) autodialog.h -o moc_autodialog.cpp

moc_cleardialog.cpp: setting.h \
		fm25v02.h \
		sparkinfo.h \
		fpga.h \
		cleardialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cleardialog.h -o moc_cleardialog.cpp

moc_coordialog.cpp: setting.h \
		coordialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) coordialog.h -o moc_coordialog.cpp

moc_groupdialog.cpp: groupdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) groupdialog.h -o moc_groupdialog.cpp

moc_jumpdialog.cpp: jumpdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) jumpdialog.h -o moc_jumpdialog.cpp

moc_keyboard.cpp: ui_keyboard.h \
		keyboard.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) keyboard.h -o moc_keyboard.cpp

moc_keydialog.cpp: setting.h \
		fm25v02.h \
		keydialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) keydialog.h -o moc_keydialog.cpp

moc_maininterface.cpp: mesgbox.h \
		qcheck.h \
		qcombox.h \
		qcomboxtime.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h \
		qindicate.h \
		qparameter.h \
		startmenu.h \
		cleardialog.h \
		keydialog.h \
		settingdialog.h \
		calibration.h \
		toplevel.h \
		seconlevel_f3.h \
		coordialog.h \
		seconlevel_f4.h \
		groupdialog.h \
		autodialog.h \
		jumpdialog.h \
		seconlevel_f5.h \
		seconlevel_f6.h \
		keyboard.h \
		ui_keyboard.h \
		qcommand.h \
		qalerts.h \
		sparkthread.h \
		scanthread.h \
		maininterface.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) maininterface.h -o moc_maininterface.cpp

moc_mesgbox.cpp: qcheck.h \
		qcombox.h \
		qcomboxtime.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h \
		qindicate.h \
		qparameter.h \
		mesgbox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mesgbox.h -o moc_mesgbox.cpp

moc_myinputpanelcontext.cpp: keyboard.h \
		ui_keyboard.h \
		myinputpanelcontext.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) myinputpanelcontext.h -o moc_myinputpanelcontext.cpp

moc_qcheck.cpp: qcheck.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qcheck.h -o moc_qcheck.cpp

moc_qcombox.cpp: qcombox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qcombox.h -o moc_qcombox.cpp

moc_qcomboxtime.cpp: qcombox.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h \
		qcomboxtime.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qcomboxtime.h -o moc_qcomboxtime.cpp

moc_qcommand.cpp: qcommand.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qcommand.h -o moc_qcommand.cpp

moc_qindicate.cpp: qindicate.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qindicate.h -o moc_qindicate.cpp

moc_qparameter.cpp: qparameter.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qparameter.h -o moc_qparameter.cpp

moc_scanthread.cpp: scanthread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) scanthread.h -o moc_scanthread.cpp

moc_seconlevel_f3.cpp: coordialog.h \
		setting.h \
		seconlevel_f3.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) seconlevel_f3.h -o moc_seconlevel_f3.cpp

moc_seconlevel_f4.cpp: groupdialog.h \
		autodialog.h \
		jumpdialog.h \
		seconlevel_f4.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) seconlevel_f4.h -o moc_seconlevel_f4.cpp

moc_seconlevel_f5.cpp: seconlevel_f5.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) seconlevel_f5.h -o moc_seconlevel_f5.cpp

moc_seconlevel_f6.cpp: seconlevel_f6.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) seconlevel_f6.h -o moc_seconlevel_f6.cpp

moc_settingdialog.cpp: setting.h \
		fm25v02.h \
		sparkinfo.h \
		fpga.h \
		settingdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) settingdialog.h -o moc_settingdialog.cpp

moc_sparkinfo.cpp: fpga.h \
		fm25v02.h \
		setting.h \
		sparkinfo.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sparkinfo.h -o moc_sparkinfo.cpp

moc_sparkthread.cpp: sparkthread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sparkthread.h -o moc_sparkthread.cpp

moc_startmenu.cpp: cleardialog.h \
		setting.h \
		fm25v02.h \
		sparkinfo.h \
		fpga.h \
		keydialog.h \
		settingdialog.h \
		calibration.h \
		startmenu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) startmenu.h -o moc_startmenu.cpp

moc_toplevel.cpp: toplevel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) toplevel.h -o moc_toplevel.cpp

moc_qalerts.cpp: sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h \
		qalerts.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qalerts.h -o moc_qalerts.cpp

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		auto.png \
		brightness_3.png \
		icon_h_e.png \
		icon_p.png \
		jump.png \
		unselected.png \
		table.png \
		password.png \
		brightness_4.png \
		calibration.png \
		en.qm \
		sleep_b.png \
		restart.png \
		unlock.png \
		sleep.png \
		icon_p_e.png \
		press.png \
		hover.png \
		setting.png \
		selected.png \
		icon_h.png \
		icon_e.png \
		sound_0.png \
		shut.png \
		sound_2.png \
		sound_1.png \
		restart_b.png \
		nomal.png \
		brightness_0.png \
		sound_3.png \
		clear.png \
		shut_b.png \
		brightness_2.png \
		brightness_1.png \
		icon.png \
		axis.png \
		ok.png \
		cancel.png
	/usr/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_autodialog.h ui_cleardialog.h ui_coordialog.h ui_groupdialog.h ui_jumpdialog.h ui_keyboard.h ui_keydialog.h ui_maininterface.h ui_mesgbox.h ui_seconlevel_f3.h ui_seconlevel_f4.h ui_seconlevel_f5.h ui_seconlevel_f6.h ui_settingdialog.h ui_startmenu.h ui_toplevel.h
compiler_uic_clean:
	-$(DEL_FILE) ui_autodialog.h ui_cleardialog.h ui_coordialog.h ui_groupdialog.h ui_jumpdialog.h ui_keyboard.h ui_keydialog.h ui_maininterface.h ui_mesgbox.h ui_seconlevel_f3.h ui_seconlevel_f4.h ui_seconlevel_f5.h ui_seconlevel_f6.h ui_settingdialog.h ui_startmenu.h ui_toplevel.h
ui_autodialog.h: autodialog.ui
	/usr/bin/uic-qt4 autodialog.ui -o ui_autodialog.h

ui_cleardialog.h: cleardialog.ui
	/usr/bin/uic-qt4 cleardialog.ui -o ui_cleardialog.h

ui_coordialog.h: coordialog.ui
	/usr/bin/uic-qt4 coordialog.ui -o ui_coordialog.h

ui_groupdialog.h: groupdialog.ui
	/usr/bin/uic-qt4 groupdialog.ui -o ui_groupdialog.h

ui_jumpdialog.h: jumpdialog.ui
	/usr/bin/uic-qt4 jumpdialog.ui -o ui_jumpdialog.h

ui_keyboard.h: keyboard.ui
	/usr/bin/uic-qt4 keyboard.ui -o ui_keyboard.h

ui_keydialog.h: keydialog.ui
	/usr/bin/uic-qt4 keydialog.ui -o ui_keydialog.h

ui_maininterface.h: maininterface.ui
	/usr/bin/uic-qt4 maininterface.ui -o ui_maininterface.h

ui_mesgbox.h: mesgbox.ui
	/usr/bin/uic-qt4 mesgbox.ui -o ui_mesgbox.h

ui_seconlevel_f3.h: seconlevel_f3.ui
	/usr/bin/uic-qt4 seconlevel_f3.ui -o ui_seconlevel_f3.h

ui_seconlevel_f4.h: seconlevel_f4.ui
	/usr/bin/uic-qt4 seconlevel_f4.ui -o ui_seconlevel_f4.h

ui_seconlevel_f5.h: seconlevel_f5.ui
	/usr/bin/uic-qt4 seconlevel_f5.ui -o ui_seconlevel_f5.h

ui_seconlevel_f6.h: seconlevel_f6.ui
	/usr/bin/uic-qt4 seconlevel_f6.ui -o ui_seconlevel_f6.h

ui_settingdialog.h: settingdialog.ui
	/usr/bin/uic-qt4 settingdialog.ui -o ui_settingdialog.h

ui_startmenu.h: startmenu.ui
	/usr/bin/uic-qt4 startmenu.ui -o ui_startmenu.h

ui_toplevel.h: toplevel.ui
	/usr/bin/uic-qt4 toplevel.ui -o ui_toplevel.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

autodialog.o: autodialog.cpp autodialog.h \
		ui_autodialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autodialog.o autodialog.cpp

cleardialog.o: cleardialog.cpp cleardialog.h \
		setting.h \
		fm25v02.h \
		sparkinfo.h \
		fpga.h \
		ui_cleardialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cleardialog.o cleardialog.cpp

coordialog.o: coordialog.cpp coordialog.h \
		setting.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		ui_coordialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o coordialog.o coordialog.cpp

fm25v02.o: fm25v02.c fm25v02.h \
		setting.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fm25v02.o fm25v02.c

fpga.o: fpga.c fpga.h \
		setting.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fpga.o fpga.c

groupdialog.o: groupdialog.cpp groupdialog.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h \
		ui_groupdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o groupdialog.o groupdialog.cpp

jumpdialog.o: jumpdialog.cpp jumpdialog.h \
		ui_jumpdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jumpdialog.o jumpdialog.cpp

keyboard.o: keyboard.cpp keyboard.h \
		ui_keyboard.h \
		en_keymap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyboard.o keyboard.cpp

keydialog.o: keydialog.cpp keydialog.h \
		setting.h \
		fm25v02.h \
		ui_keydialog.h \
		sparkinfo.h \
		fpga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keydialog.o keydialog.cpp

main.o: main.cpp maininterface.h \
		mesgbox.h \
		qcheck.h \
		qcombox.h \
		qcomboxtime.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h \
		qindicate.h \
		qparameter.h \
		startmenu.h \
		cleardialog.h \
		keydialog.h \
		settingdialog.h \
		calibration.h \
		toplevel.h \
		seconlevel_f3.h \
		coordialog.h \
		seconlevel_f4.h \
		groupdialog.h \
		autodialog.h \
		jumpdialog.h \
		seconlevel_f5.h \
		seconlevel_f6.h \
		keyboard.h \
		ui_keyboard.h \
		qcommand.h \
		qalerts.h \
		sparkthread.h \
		scanthread.h \
		myinputpanelcontext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

maininterface.o: maininterface.cpp maininterface.h \
		mesgbox.h \
		qcheck.h \
		qcombox.h \
		qcomboxtime.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h \
		qindicate.h \
		qparameter.h \
		startmenu.h \
		cleardialog.h \
		keydialog.h \
		settingdialog.h \
		calibration.h \
		toplevel.h \
		seconlevel_f3.h \
		coordialog.h \
		seconlevel_f4.h \
		groupdialog.h \
		autodialog.h \
		jumpdialog.h \
		seconlevel_f5.h \
		seconlevel_f6.h \
		keyboard.h \
		ui_keyboard.h \
		qcommand.h \
		qalerts.h \
		sparkthread.h \
		scanthread.h \
		ui_maininterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maininterface.o maininterface.cpp

mesgbox.o: mesgbox.cpp mesgbox.h \
		qcheck.h \
		qcombox.h \
		qcomboxtime.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h \
		qindicate.h \
		qparameter.h \
		ui_mesgbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mesgbox.o mesgbox.cpp

myinputpanelcontext.o: myinputpanelcontext.cpp myinputpanelcontext.h \
		keyboard.h \
		ui_keyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myinputpanelcontext.o myinputpanelcontext.cpp

qcheck.o: qcheck.cpp qcheck.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcheck.o qcheck.cpp

qcombox.o: qcombox.cpp qcombox.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcombox.o qcombox.cpp

qcomboxtime.o: qcomboxtime.cpp qcomboxtime.h \
		qcombox.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcomboxtime.o qcomboxtime.cpp

qcommand.o: qcommand.cpp qcommand.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcommand.o qcommand.cpp

qindicate.o: qindicate.cpp qindicate.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qindicate.o qindicate.cpp

qparameter.o: qparameter.cpp qparameter.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qparameter.o qparameter.cpp

scanthread.o: scanthread.cpp scanthread.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h \
		sparkthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scanthread.o scanthread.cpp

seconlevel_f3.o: seconlevel_f3.cpp seconlevel_f3.h \
		coordialog.h \
		setting.h \
		ui_seconlevel_f3.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o seconlevel_f3.o seconlevel_f3.cpp

seconlevel_f4.o: seconlevel_f4.cpp maininterface.h \
		mesgbox.h \
		qcheck.h \
		qcombox.h \
		qcomboxtime.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h \
		qindicate.h \
		qparameter.h \
		startmenu.h \
		cleardialog.h \
		keydialog.h \
		settingdialog.h \
		calibration.h \
		toplevel.h \
		seconlevel_f3.h \
		coordialog.h \
		seconlevel_f4.h \
		groupdialog.h \
		autodialog.h \
		jumpdialog.h \
		seconlevel_f5.h \
		seconlevel_f6.h \
		keyboard.h \
		ui_keyboard.h \
		qcommand.h \
		qalerts.h \
		sparkthread.h \
		scanthread.h \
		ui_seconlevel_f4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o seconlevel_f4.o seconlevel_f4.cpp

seconlevel_f5.o: seconlevel_f5.cpp seconlevel_f5.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h \
		ui_seconlevel_f5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o seconlevel_f5.o seconlevel_f5.cpp

seconlevel_f6.o: seconlevel_f6.cpp seconlevel_f6.h \
		ui_seconlevel_f6.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o seconlevel_f6.o seconlevel_f6.cpp

settingdialog.o: settingdialog.cpp settingdialog.h \
		setting.h \
		fm25v02.h \
		sparkinfo.h \
		fpga.h \
		ui_settingdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingdialog.o settingdialog.cpp

sparkinfo.o: sparkinfo.cpp sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sparkinfo.o sparkinfo.cpp

sparkthread.o: sparkthread.cpp sparkthread.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sparkthread.o sparkthread.cpp

startmenu.o: startmenu.cpp startmenu.h \
		cleardialog.h \
		setting.h \
		fm25v02.h \
		sparkinfo.h \
		fpga.h \
		keydialog.h \
		settingdialog.h \
		calibration.h \
		ui_startmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o startmenu.o startmenu.cpp

toplevel.o: toplevel.cpp toplevel.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h \
		ui_toplevel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toplevel.o toplevel.cpp

qalerts.o: qalerts.cpp qalerts.h \
		sparkinfo.h \
		fpga.h \
		fm25v02.h \
		setting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qalerts.o qalerts.cpp

calibration.o: calibration.cpp calibration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibration.o calibration.cpp

moc_autodialog.o: moc_autodialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_autodialog.o moc_autodialog.cpp

moc_cleardialog.o: moc_cleardialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cleardialog.o moc_cleardialog.cpp

moc_coordialog.o: moc_coordialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_coordialog.o moc_coordialog.cpp

moc_groupdialog.o: moc_groupdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_groupdialog.o moc_groupdialog.cpp

moc_jumpdialog.o: moc_jumpdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_jumpdialog.o moc_jumpdialog.cpp

moc_keyboard.o: moc_keyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keyboard.o moc_keyboard.cpp

moc_keydialog.o: moc_keydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keydialog.o moc_keydialog.cpp

moc_maininterface.o: moc_maininterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maininterface.o moc_maininterface.cpp

moc_mesgbox.o: moc_mesgbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mesgbox.o moc_mesgbox.cpp

moc_myinputpanelcontext.o: moc_myinputpanelcontext.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myinputpanelcontext.o moc_myinputpanelcontext.cpp

moc_qcheck.o: moc_qcheck.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcheck.o moc_qcheck.cpp

moc_qcombox.o: moc_qcombox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcombox.o moc_qcombox.cpp

moc_qcomboxtime.o: moc_qcomboxtime.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcomboxtime.o moc_qcomboxtime.cpp

moc_qcommand.o: moc_qcommand.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcommand.o moc_qcommand.cpp

moc_qindicate.o: moc_qindicate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qindicate.o moc_qindicate.cpp

moc_qparameter.o: moc_qparameter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qparameter.o moc_qparameter.cpp

moc_scanthread.o: moc_scanthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scanthread.o moc_scanthread.cpp

moc_seconlevel_f3.o: moc_seconlevel_f3.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_seconlevel_f3.o moc_seconlevel_f3.cpp

moc_seconlevel_f4.o: moc_seconlevel_f4.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_seconlevel_f4.o moc_seconlevel_f4.cpp

moc_seconlevel_f5.o: moc_seconlevel_f5.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_seconlevel_f5.o moc_seconlevel_f5.cpp

moc_seconlevel_f6.o: moc_seconlevel_f6.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_seconlevel_f6.o moc_seconlevel_f6.cpp

moc_settingdialog.o: moc_settingdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingdialog.o moc_settingdialog.cpp

moc_sparkinfo.o: moc_sparkinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sparkinfo.o moc_sparkinfo.cpp

moc_sparkthread.o: moc_sparkthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sparkthread.o moc_sparkthread.cpp

moc_startmenu.o: moc_startmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_startmenu.o moc_startmenu.cpp

moc_toplevel.o: moc_toplevel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toplevel.o moc_toplevel.cpp

moc_qalerts.o: moc_qalerts.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qalerts.o moc_qalerts.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

